CREATE DATABASE IF NOT EXISTS hakeem_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE hakeem_db;


CREATE TABLE IF NOT EXISTS patients (
patient_name VARCHAR(150) NOT NULL,
problem VARCHAR(150) NOT NULL,
dob DATE NULL,
address TEXT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
mobile VARCHAR(20) NULL,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS appointments (
patient_name VARCHAR(150) NOT NULL,
doctor VARCHAR(150) NOT NULL,
appointment_date DATE NOT NULL,
appointment_time TIME NULL,
note TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS feedback (
patient_name VARCHAR(50) NOT NULL,
email VARCHAR(150) NULL,
message TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);